version: 2

models:
  - name: int_activity_mobile_data_activity
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     data_tests:
    #       - unique
    #       - not_null

  - name: int_activity_sms_record 
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     data_tests:
    #       - unique
    #       - not_null

  - name: int_activity_voice_call_record
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     data_tests:
    #       - unique
    #       - not_null

  - name: int_subscriber
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     data_tests:
    #       - unique
    #       - not_null